name: Cancer Stats Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight

jobs:
  fetch-process-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python scripts/process_cancer_data.py
